require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.4
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - bin/bundle

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
