sdr_api:
  days_after_which_to_remove_uploads: 7
  blob_batch_size: 20
  ingest_retries: 5

dor_services:
  url: 'http://localhost:3003'
  # To generate the token: docker-compose run dor-services-app rake generate_token
  token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGb28ifQ.-BVfLTW9Q1_ZQEsGv4tuzGLs5rESN7LgdtEwUltnKv4

workflow:
  url: 'http://localhost:3001'

staging_location: '/dor/workspace'


# This user is allowed to proxy other users, we expect that it'll be argo and it
# will be responible for only proxying users which it has verififed with Shibboleth.
argo_user: argo@dlss.sul.stanford.edu
